### ISSUE TITLE
Publish new version to NPM for react-native 0.47 compatibility

### ISSUE THREAD

**Issue by jordanmkoncz** [vovkasm/react-native-web-image#11]
Thanks for creating a great library! Can you please publish a new version of this package to NPM which has all of the latest commits. I'm using this library with `react-native` `0.47.1` so I need the recent changes to make this library compatible with this version of `react-native`, but currently there's no version on NPM that includes these changes.

In the meantime if anyone else is running into this issue, you can update your `package.json` to specifically reference the latest commit, I did this by running `yarn add git+ssh://git@github.com/vovkasm/react-native-web-image.git#4fb5baf626b29e57241584af06254033fe35f892`.

**Comment by vovkasm** [comment]
I can, but the current Android functional is not comparable to that of iOS (iOS still lacks some functional) :-(
If this is OK then I will... I think I could try to find some time this week and implement lacking functional...

**Comment by jordanmkoncz** [comment]
@vovkasm Personally I think publishing the new version should not be delayed by getting Android/iOS functionality comparable, as there are users of the library who cannot use a version of this library from NPM if they're on `react-native` `0.47` or later.

I suggest publishing a new version to NPM as soon as possible which has these changes to make the library compatible with the latest versions of `react-native`, and then later when the new changes for Android have been completed, publishing another new version to NPM.

Another reason for this is that with my solution of pulling down a specific commit via git (instead of NPM), you run into this issue https://github.com/vovkasm/react-native-web-image/issues/8 which prevents you from creating a build in Xcode. So right now, if you're on `react-native` `0.47` or later you cannot create a build of the app in Xcode if you're using `react-native-web-image`.

**Comment by vovkasm** [comment]
Done. Version 0.0.5 should support RN >=0.47. Also #8 should be resolved now.

**Comment by jordanmkoncz** [comment]
Thanks @vovkasm.
