### ISSUE TITLE
How to remove image cache ?

### ISSUE THREAD

**Issue by Najibsaurus** [vovkasm/react-native-web-image#12]
I would like to delete cache of image. Could this library handle it ?

**Comment by vovkasm** [comment]
Currently no way. SDWebImage and Glide have some methods, but they are not exposed to js. Currently it not the high priority to me, also pull requests are welcome!

Note that best strategy to update cached images is change url, so in reality it should be rare need to clear the cache.

**Comment by Najibsaurus** [comment]
Okay, thanks a lot
